BookShelf/Areas/Admin/Controllers/CopyTypeController.cs
using BookShelf.DataAccess;
using BookShelf.DataAccess.Repository.IRepository;
using BookShelf.Models;
using BookShelf.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookShelf.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CopyTypeController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        public CopyTypeController(IUnitOfWork unitofwork)
        {
            _unitofwork = unitofwork;
        }
        public IActionResult Index()
        {
            IEnumerable<CopyType> objcopytype = _unitofwork.CopyType.GetAll();
            return View(objcopytype);
        }
        public IActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CopyType copyType)
        {

            if (ModelState.IsValid)
            {
                _unitofwork.CopyType.Add(copyType);
                _unitofwork.Save();
                TempData["success"] = "Copy Type Created Successfully";
                return RedirectToAction("Index");
            }
            return View(copyType);
        }     
        
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var copyTypefromDb = _unitofwork.CopyType.GetFirstOrDefault(u => u.Id == id);
            if (copyTypefromDb == null)
            {
                return NotFound();
            }
            return View(copyTypefromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CopyType copyType)
        {
            if (ModelState.IsValid)
            {
                _unitofwork.CopyType.Update(copyType);
                _unitofwork.Save();
                TempData["success"] = "Copy Type Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(copyType);
        }    
        
        public IActionResult Delete(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var copyTypefromDb = _unitofwork.CopyType.GetFirstOrDefault(u => u.Id == id);
            if (copyTypefromDb == null)
            {
                return NotFound();
            }
            return View(copyTypefromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitofwork.CopyType.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitofwork.CopyType.Remove(obj);
                _unitofwork.Save();
            TempData["success"] = "Copy Type Deleted Successfully";
            return RedirectToAction("Index");
            
          
        }


    }
}

BookShelf/Areas/Admin/Views/CopyType/Create.cshtml
@model CopyType
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-1">
            <h2 class="text-primary">Create Copy Type</h2>
        </div>
        <hr />
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
           
        </div> 

        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a class="btn btn-secondary" asp-controller="CopyType" asp-action="Index" style="width:150px">Back To List</a>
    </div>


</form>
@section scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

BookShelf/Areas/Admin/Views/CopyType/Delete.cshtml
@model CopyType
<form method="post" asp-action="DeletePOST">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-1">
            <h2 class="text-primary">Delete Copy-Type</h2>
        </div>
        <hr />
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
            
           
        </div> 

        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a class="btn btn-secondary" asp-controller="CopyType" asp-action="Index" style="width:150px">Back To List</a>
    </div>


</form>
@section scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

BookShelf/Areas/Admin/Views/CopyType/Edit.cshtml
@model CopyType
<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-1">
            <h2 class="text-primary">Edit Copy-Type</h2>
        </div>
        <hr />
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
           
        </div> 

        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a class="btn btn-secondary" asp-controller="CopyType" asp-action="Index" style="width:150px">Back To List</a>
    </div>


</form>
@section scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

BookShelf/Areas/Admin/Views/CopyType/Index.cshtml
@model IEnumerable<CopyType>
<partial name="_Notification" />
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h1 class="text-primary">Copy-Type List</h1>
        </div>

        <div class="col-6 text-end pt-2">
            <a asp-controller="CopyType" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle"></i> Create New Copy-Type</a>
        </div>

    </div>
</div><br />


<table class="table table-border table-striped ">
<thead>
    <tr>
        <th>CopyType Name</th>
        
        <th>Action</th>
    </tr>
</thead>
<tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td>@obj.Name</td>
               
                <td>
                    <div class="w-50 btn-group" role="group">
                    <a asp-controller="CopyType" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a> | 
                    <a asp-controller="CopyType" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2"><i class="bi bi-trash"></i>Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>