BookShelf/Areas/Admin/Controllers/CategoryController.cs
using BookShelf.DataAccess;
using BookShelf.DataAccess.Repository.IRepository;
using BookShelf.Models;
using BookShelf.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookShelf.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class CategoryController : Controller
    {
       private readonly IUnitOfWork _unitofwork;
        public CategoryController(IUnitOfWork unitofwork)
        {
            _unitofwork = unitofwork;
        } 
        public IActionResult Index()
        {
            IEnumerable<Category> objcategory = _unitofwork.Category.GetAll();
            return View(objcategory);
        }
        public IActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
          
            if (ModelState.IsValid)
            {
                _unitofwork.Category.Add(category);
                _unitofwork.Save();
                TempData["success"] = "Category Created Successfully";
                return RedirectToAction("Index");
            }
            return View(category);
        }   
        
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryfromDb = _db.Categories.Find(id);
            var categoryfromDb = _unitofwork.Category.GetFirstOrDefault(u=> u.Id==id);
            if (categoryfromDb==null)
            {
                return NotFound();
            }
            return View(categoryfromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
           
            if (ModelState.IsValid)
            {
                _unitofwork.Category.Update(category);
                _unitofwork.Save();
                TempData["success"] = "Category Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(category);
        }    
        
        public IActionResult Delete(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var categoryfromDb = _unitofwork.Category.GetFirstOrDefault(u => u.Id==id);
            if (categoryfromDb==null)
            {
                return NotFound();
            }
            return View(categoryfromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitofwork.Category.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitofwork.Category.Remove(obj);
            _unitofwork.Save();
            TempData["success"] = "Category Deleted Successfully";
            return RedirectToAction("Index");
            
          
        }


    }
}

BookShelf/Areas/Admin/Controllers/CompanyController.cs
using BookShelf.DataAccess;
using BookShelf.DataAccess.Repository.IRepository;
using BookShelf.Models;
using BookShelf.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookShelf.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class  CompanyController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        
        public CompanyController(IUnitOfWork unitofwork)
        {
            _unitofwork = unitofwork;
            
            
        }
        public IActionResult Index()
        {
            
            return View();
        }
    
        //Get Create and Update
        public IActionResult Upsert(int? id)
        {
           
            Company company = new();
            if(id == null || id == 0)
            {
                //Create Product
                return View(company);
            }
            else
            {
                Company company1= _unitofwork.Company.GetFirstOrDefault(u => u.Id == id);

                return View(company1);
                //Update Product

            }
            
           
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company company, IFormFile? file )
        {
            if (ModelState.IsValid)
            {
                if (company.Id == 0)
                {
                    _unitofwork.Company.Add(company);
                    TempData["success"] = "Company Created Successfully";
                }
                else
                {
                    _unitofwork.Company.Update(company);
                    TempData["success"] = "Company Updated Successfully";
                }
              
                _unitofwork.Save();
                
                return RedirectToAction("Index");
            }
            return View(company);
        }    
        

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var CompanyList = _unitofwork.Company.GetAll();
            return Json(new{ data=CompanyList});
        }
        [HttpDelete]
        
        public IActionResult Delete(int? id)
        {
            var obj = _unitofwork.Company.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }
            _unitofwork.Company.Remove(obj);
            _unitofwork.Save();
            return Json(new { success = true, message = "Delete Successfully" });
            return RedirectToAction("Index");


        }
        #endregion


    }
}

BookShelf/Areas/Admin/Controllers/ProductController.cs
using BookShelf.DataAccess;
using BookShelf.DataAccess.Repository.IRepository;
using BookShelf.Models;
using BookShelf.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookShelf.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitofwork, IWebHostEnvironment webHostEnvironment)
        {
            _unitofwork = unitofwork;
            _webHostEnvironment = webHostEnvironment;
            
        }
        public IActionResult Index()
        {
            
            return View();
        }
    
        //Get Create and Update
        public IActionResult Upsert(int? id)
        {
            IEnumerable<SelectListItem> CategoryList = _unitofwork.Category.GetAll().Select(
                u=> new SelectListItem
                {
                    Text=u.Name,
                    Value=u.Id.ToString()
                }
                );
            IEnumerable<SelectListItem> CopyTypeList = _unitofwork.CopyType.GetAll().Select(
                u => new SelectListItem
                 {
                    Text = u.Name,
                    Value = u.Id.ToString()
                 }
                 );

            Product product = new();
            if(id == null || id == 0)
            {
                //Create Product
                ViewBag.CategoryList=CategoryList;
                ViewBag.CopyTypeList=CopyTypeList;
                return View(product);
            }
            else
            {
                Product product1= _unitofwork.Product.GetFirstOrDefault(u => u.Id == id);
                ViewBag.CategoryList = CategoryList;
                ViewBag.CopyTypeList = CopyTypeList;
                return View(product1);
                //Update Product

            }
            
           
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Product product, IFormFile? file )
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var upload = Path.Combine(wwwRootPath,@"images\products");
                    var extension=Path.GetExtension(file.FileName);

                    if (product.ImageUrl != null)
                    {
                        var OldImage = Path.Combine(wwwRootPath, product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(OldImage))
                        {
                            System.IO.File.Delete(OldImage);
                        }
                    }


                    using(var fileStream = new FileStream(Path.Combine(upload,fileName+extension), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    product.ImageUrl = @"images\products\" + fileName + extension;
                }
                if (product.Id == 0)
                {
                    _unitofwork.Product.Add(product);
                    TempData["success"] = "Product Created Successfully";
                }
                else
                {
                    _unitofwork.Product.Update(product);
                    TempData["success"] = "Product Updated Successfully";
                }
              
                _unitofwork.Save();
                
                return RedirectToAction("Index");
            }
            return View(product);
        }    
        

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitofwork.Product.GetAll(includeProperties: "Category,CopyType");
            return Json(new{ data=productList});
        }
        [HttpDelete]
        
        public IActionResult Delete(int? id)
        {
            var obj = _unitofwork.Product.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }
            var OldImage = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(OldImage))
            {
                System.IO.File.Delete(OldImage);
            }
            _unitofwork.Product.Remove(obj);
            _unitofwork.Save();
            return Json(new { success = true, message = "Delete Successfully" });
            return RedirectToAction("Index");


        }
        #endregion


    }
}

BookShelf/ViewComponents/ShoppingCartViewComponent.cs
using BookShelf.DataAccess.Repository.IRepository;
using BookShelf.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BookShelf.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var ClaimIdentity = (ClaimsIdentity)User.Identity;
            var claim = ClaimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
                {
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                else
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count);
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }

            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);

            }
        }
    }
}

BookShelf/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using BookShelf.Utility
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookShelf</title>
    <link href="c:\users\ashar125\onedrive\desktop\bookshelf\bookshelfweb\bookshelf\wwwroot\css\bootstrap55.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/Bootstrap55.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookShelf.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index"><b>BOOK-SHELF</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole(SD.Role_Admin))
                        {

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Managment</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CopyType" asp-action="Index">CopyType</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                </div>
                            </li>
                        }

                        <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a></li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>



                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="pt-2 footer text-muted bg-primary" style="margin-top:14%;">
        <div class="container footer">
            &copy; 2023 - BOOK-SHELF By ASHAR RASHEED
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookShelf/Views/Shared/_Notification.cshtml
@if(TempData["success"]!=null)
{   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.success('@TempData["success"]');
    </script>
    
}
@if(TempData["error"]!=null)
{
      <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.success('@TempData["error"]');
    </script>
}